AWSTemplateFormatVersion: 2010-09-09
Description: Sets up AWS resources used to deploy auto-qc-pipeline

Parameters:
  StackPrefix:
    Description: A prefix that identifies this stack
    Type: String
  DeploymentBucketName:
    Description: The bucket used to deploy cloudformation resources
    Type: String
  EnvironmentType:
    Description: The deployment environment type
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - dev

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Application
          Value: auto-qc-pipeline
        - Key: StackPrefix
          Value: !Ref StackPrefix
      BucketName: !Ref DeploymentBucketName


Outputs:
  DeploymentBucketOutput:
    Description: The bucket used to deploy cloudformation resources
    Value: !Ref DeploymentBucketName
    Export:
      Name: !Sub ${StackPrefix}-auto-qc-pipeline-deployment-bucket
  EnvironmentTypeOutput:
    Description: The deployment environment type
    Value: !Ref EnvironmentType
    Export:
      Name: !Sub ${StackPrefix}-auto-qc-pipeline-environment-type
