version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: 'logging.StreamHandler'
    formatter': 'simple'
    stream': 'ext://sys.stdout'
loggers:
  eipiphany:
    level: 'INFO'
    handlers:
      - 'console'
    propagate: false
  autoqc:
    level: 'DEBUG'
    handlers:
      - 'console'
    propagate: false
  cotede:
    level: 'WARNING'
    handlers:
      - 'console'
    propagate: false
root:
  level: 'INFO'
  handlers:
    - 'console'